begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  barcode text unique,
  stock integer not null default 0 check (stock >= 0),
  cost integer not null,
  price integer not null,
  min_stock integer not null default 300,
  unit text not null default 'unidad',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  type text not null check (type in ('initial', 'entry', 'output')),
  quantity integer not null check (quantity > 0),
  delta integer not null,
  reason text not null,
  lot text,
  expiration_date date,
  note text,
  source text not null default 'manual' check (source in ('manual', 'scanner')),
  reference text unique,
  user_id text not null,
  user_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists movements_product_created_idx
  on public.movements(product_id, created_at desc, id desc);

create table if not exists public.label_prints (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  label_size text not null check (label_size in ('standard', 'compact')),
  printed_by_user_id text not null,
  printed_by_user_name text not null,
  printed_at timestamptz not null default now(),
  used_at timestamptz,
  used_by_user_id text,
  used_movement_reference text unique
);

create index if not exists label_prints_product_created_idx
  on public.label_prints(product_id, printed_at desc, id desc);

create table if not exists public.app_users_v2 (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  username text unique,
  password_hash text,
  password_salt text,
  must_change_password boolean not null default true,
  failed_login_attempts integer not null default 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  role text not null check (role in ('owner', 'admin', 'warehouse', 'dispatch', 'viewer')),
  can_view_cost boolean not null default false,
  can_manage_users boolean not null default false,
  active boolean not null default false,
  system_account boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_sessions_v2 (
  id text primary key,
  user_id bigint not null references public.app_users_v2(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists app_sessions_expires_idx on public.app_sessions_v2(expires_at);

insert into public.products (id, name, sku, stock, cost, price, min_stock, unit, active)
values (1, 'LinaDigest', 'LD-400G', 1438, 12000, 29990, 300, 'frasco 400 g', true)
on conflict (id) do nothing;

insert into public.movements
  (id, product_id, type, quantity, delta, reason, note, source, user_id, user_name)
values
  (1, 1, 'initial', 2029, 2029, 'Stock inicial', 'Cantidad inicial corregida; saldo disponible conservado', 'manual', 'system', 'Sistema LinaDigest')
on conflict (id) do update set
  quantity = excluded.quantity,
  delta = excluded.delta,
  note = excluded.note;

insert into public.app_users_v2
  (id, name, username, role, can_view_cost, can_manage_users, active, system_account)
values
  (101, 'Bodega', 'bodega', 'warehouse', false, false, true, false),
  (102, 'Despacho', 'despacho', 'dispatch', false, false, true, false),
  (103, 'Miguel Angel', 'miguel', 'admin', true, true, true, false),
  (104, 'Daniela Vasquez', 'daniela', 'admin', true, true, true, false)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select coalesce(max(id), 1) from public.products), 1), true);
select setval(pg_get_serial_sequence('public.movements', 'id'), greatest((select coalesce(max(id), 1) from public.movements), 1), true);
select setval(
  pg_get_serial_sequence('public.label_prints', 'id'),
  coalesce((select max(id) from public.label_prints), 1),
  exists(select 1 from public.label_prints)
);
select setval(pg_get_serial_sequence('public.app_users_v2', 'id'), greatest((select coalesce(max(id), 1) from public.app_users_v2), 1), true);

create or replace function public.register_inventory_movement(
  p_product_id bigint,
  p_type text,
  p_quantity integer,
  p_reason text,
  p_lot text,
  p_expiration_date date,
  p_note text,
  p_user_id text,
  p_user_name text
)
returns table(new_stock integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock integer;
  v_delta integer;
begin
  if p_type not in ('entry', 'output') or p_quantity < 1 then
    raise exception 'invalid_movement' using errcode = '22023';
  end if;

  select p.stock into v_stock
  from public.products p
  where p.id = p_product_id
  for update;

  if not found then
    raise exception 'product_not_found' using errcode = 'P0002';
  end if;

  v_delta := case when p_type = 'entry' then p_quantity else -p_quantity end;
  if v_stock + v_delta < 0 then
    raise exception 'insufficient_stock:%', v_stock using errcode = 'P0001';
  end if;

  update public.products
  set stock = stock + v_delta, updated_at = now()
  where id = p_product_id
  returning stock into new_stock;

  insert into public.movements
    (product_id, type, quantity, delta, reason, lot, expiration_date, note, source, user_id, user_name)
  values
    (p_product_id, p_type, p_quantity, v_delta, p_reason, p_lot, p_expiration_date, p_note, 'manual', p_user_id, p_user_name);

  return next;
end;
$$;

create or replace function public.scan_inventory_output(
  p_barcode text,
  p_scan_id text,
  p_user_id text,
  p_user_name text
)
returns table(status text, product_id bigint, product_name text, stock integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint;
  v_product_name text;
  v_stock integer;
  v_label_id bigint;
  v_label_used_at timestamptz;
begin
  select m.product_id into v_product_id
  from public.movements m
  where m.reference = p_scan_id;

  if found then
    select p.name, p.stock into v_product_name, v_stock
    from public.products p where p.id = v_product_id;
    status := 'duplicate'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
    return next; return;
  end if;

  if p_barcode ~* '^LD-[0-9]{3,18}$' then
    v_label_id := substring(p_barcode from 4)::bigint;
    select lp.product_id, lp.used_at into v_product_id, v_label_used_at
    from public.label_prints lp
    where lp.id = v_label_id
    for update;

    if not found then
      status := 'unknown_barcode'; product_id := null; product_name := null; stock := null;
      return next; return;
    end if;

    select p.name, p.stock into v_product_name, v_stock
    from public.products p
    where p.id = v_product_id
    for update;

    if v_label_used_at is not null then
      status := 'label_already_used'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
      return next; return;
    end if;
  else
    select p.id, p.name, p.stock into v_product_id, v_product_name, v_stock
    from public.products p
    where p.barcode = p_barcode
    for update;
  end if;

  if not found then
    status := 'unknown_barcode'; product_id := null; product_name := null; stock := null;
    return next; return;
  end if;
  if v_stock < 1 then
    status := 'out_of_stock'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
    return next; return;
  end if;

  begin
    insert into public.movements
      (product_id, type, quantity, delta, reason, note, source, reference, user_id, user_name)
    values
      (
        v_product_id,
        'output',
        1,
        -1,
        'Salida por escáner',
        case when v_label_id is null then 'Código ' else 'Código único ' end || p_barcode,
        'scanner',
        p_scan_id,
        p_user_id,
        p_user_name
      );
  exception when unique_violation then
    select p.stock into v_stock from public.products p where p.id = v_product_id;
    status := 'duplicate'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
    return next; return;
  end;

  if v_label_id is not null then
    update public.label_prints
    set used_at = now(), used_by_user_id = p_user_id, used_movement_reference = p_scan_id
    where id = v_label_id and used_at is null;

    if not found then
      status := 'label_already_used'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
      return next; return;
    end if;
  end if;

  update public.products
  set stock = stock - 1, updated_at = now()
  where id = v_product_id
  returning products.stock into v_stock;

  status := 'recorded'; product_id := v_product_id; product_name := v_product_name; stock := v_stock;
  return next;
end;
$$;

create or replace function public.undo_inventory_scan(
  p_scan_id text,
  p_user_id text,
  p_user_name text,
  p_can_manage boolean
)
returns table(status text, stock integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_movement_id bigint;
  v_product_id bigint;
  v_movement_user_id text;
  v_stock integer;
  v_undo_note text := 'Anulación de lectura ' || p_scan_id;
begin
  select m.id, m.product_id, m.user_id
  into v_movement_id, v_product_id, v_movement_user_id
  from public.movements m
  where m.reference = p_scan_id and m.source = 'scanner'
  for update;

  if not found then
    status := 'missing'; stock := null;
    return next; return;
  end if;

  if v_movement_user_id <> p_user_id and not p_can_manage then
    status := 'forbidden'; stock := null;
    return next; return;
  end if;

  perform 1
  from public.movements m
  where m.product_id = v_product_id and m.type = 'entry' and m.note = v_undo_note
  for update;

  if found then
    select p.stock into v_stock from public.products p where p.id = v_product_id;
    status := 'already_undone'; stock := v_stock;
    return next; return;
  end if;

  select p.stock into v_stock
  from public.products p
  where p.id = v_product_id
  for update;

  update public.products
  set stock = stock + 1, updated_at = now()
  where id = v_product_id
  returning products.stock into v_stock;

  insert into public.movements
    (product_id, type, quantity, delta, reason, note, source, user_id, user_name)
  values
    (v_product_id, 'entry', 1, 1, 'Anulación de salida por escáner', v_undo_note, 'manual', p_user_id, p_user_name);

  update public.label_prints
  set used_at = null, used_by_user_id = null, used_movement_reference = null
  where used_movement_reference = p_scan_id;

  status := 'undone'; stock := v_stock;
  return next;
end;
$$;

alter table public.products enable row level security;
alter table public.movements enable row level security;
alter table public.label_prints enable row level security;
alter table public.app_users_v2 enable row level security;
alter table public.app_sessions_v2 enable row level security;

revoke all on public.products, public.movements, public.label_prints, public.app_users_v2, public.app_sessions_v2 from anon, authenticated;
revoke execute on function public.register_inventory_movement(bigint,text,integer,text,text,date,text,text,text) from public, anon, authenticated;
revoke execute on function public.scan_inventory_output(text,text,text,text) from public, anon, authenticated;
revoke execute on function public.undo_inventory_scan(text,text,text,boolean) from public, anon, authenticated;
grant all on public.products, public.movements, public.label_prints, public.app_users_v2, public.app_sessions_v2 to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.register_inventory_movement(bigint,text,integer,text,text,date,text,text,text) to service_role;
grant execute on function public.scan_inventory_output(text,text,text,text) to service_role;
grant execute on function public.undo_inventory_scan(text,text,text,boolean) to service_role;

commit;
